### ISSUE TITLE
This a bigger scam than devhaxx 0.1

### ISSUE THREAD

**Issue by Scaroontop** [devtech-fr/test-service#1]
Bro thought he cracked devhaxx

**Comment by devtech-fr** [comment]
> Bro thought he cracked devhaxx

if it was fake then why did darian ban me and drip from the discord server because it isn't malware and you can deobfuscate the code for yourself to see and i've already demonstrated a proof of concept of it working with the exact same code pasted from the github and once again if it was fake why are you guys begging for drip to take down the repo (he doesn't even own it retard) we just uploaded it together 💀

**Comment by devtech-fr** [comment]
<img src="https://media.discordapp.net/attachments/1182465515558543410/1231995339934928937/image.png?ex=6638fc12&amp;is=66268712&amp;hm=35cff9d4c7c0d9f23eb22926a8c7b80f3c48045ad7e8023c035fb989bf43842d&amp;=&amp;format=webp&amp;quality=lossless" alt="Image"/>

**Comment by justDarian** [comment]
of course

**Comment by Scaroontop** [comment]
ong

**Comment by Scaroontop** [comment]
I nob
